import type {Config} from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sora: ['var(--font-sora)', 'sans-serif'],
        inter: ['var(--font-inter)', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-sora)'],
        'label-md': ['var(--font-inter)'],
        'headline-md': ['var(--font-sora)'],
        'label-sm': ['var(--font-inter)'],
        'headline-xl': ['var(--font-sora)'],
        'body-lg': ['var(--font-inter)'],
        'body-md': ['var(--font-inter)'],
        'headline-lg': ['var(--font-sora)'],
      },
      colors: {
        background: '#faf8ff',
        foreground: '#131b2e',
        primary: {
          DEFAULT: '#4343d5',
          container: '#5d5fef',
          fixed: '#e1e0ff',
          foreground: '#ffffff',
          'fixed-dim': '#c1c1ff',
        },
        secondary: {
          DEFAULT: '#006b5e',
          container: '#4bf8de',
          fixed: '#4ffbe1',
          'fixed-dim': '#1adec5',
        },
        tertiary: {
          DEFAULT: '#914300',
          container: '#b75600',
          fixed: '#ffdbc8',
          'fixed-dim': '#ffb68b',
        },
        surface: {
          DEFAULT: '#faf8ff',
          container: '#eaedff',
          variant: '#dae2fd',
          dim: '#d2d9f4',
          bright: '#faf8ff',
          'container-low': '#f2f3ff',
          'container-high': '#e2e7ff',
          'container-lowest': '#ffffff',
        },
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-surface': '#131b2e',
        'on-surface-variant': '#464555',
        'on-primary-container': '#faf7ff',
        'on-secondary-container': '#006f62',
        'on-tertiary-container': '#fff6f3',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        outline: {
          DEFAULT: '#767586',
          variant: '#c7c4d7',
        },
        'outline-variant': '#c7c4d7',
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        'on-error': '#ffffff',
        border: '#c7c4d7',
        input: '#eaedff',
        ring: '#4343d5',
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
      borderRadius: {
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '2rem',
        '3xl': '2.5rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'margin-desktop': '80px',
        base: '8px',
        xs: '4px',
        sm: '12px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '16px',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
